---
title: "Worksheet 1-4"
author: "Manuel Rosero"
date: "10/26/2016"
output: html_document
---

#Worksheet 1 - welcome to R

Welcome to the second part of the Bioinformatics class! 

As you know, the first part of the class focused on Perl, the command line and emacs. This second part of the class will focus on R. It is taught by me, Daniel Fulop. We'll do R for 5 weeks and after that, you have another 3.5 weeks to work on your projects. 

In this class, you will be mostly working by yourself or with a partner. You get worksheets and work at your own pace. Worksheets are due 1 week after they're assigned in class. If you turn them in late, you will be deducted 10% for each day late. I am working on a means of digital submission of worksheets ~~probably through iLearn~~ through GitHub.

**Task 1** - Be a class ambassador and visit my office hours. 

**Goal:** Each day of the course (except day 1), I would like to know how you are doing. I also would like to get to know everyone. Each of you should therefore sign up to come to my office hours once during the coming 5 weeks. My office hours are Tuesday and Thursday 1:30-2:30. Use this sign up spreadsheet: https://goo.gl/4rw9i6


When you come to my office hours (probably with a colleague), be prepared to tell me at least one thing you found interesting in the last class and one thing you found confusing, hard or boring. Office hours will be held in this computer lab.

**Did you sign up for an office hour meeting?**

~~Yes~~ / No


Name: Manuel Rosero 


Date: 10/27/16

***  
#Worksheet 2 - R inspiration

R is a software environment and programming language for statistics that is used by many people, among them many biologists. The goal of this worksheet is for you to find inspiration to learn R by reading about how other people use R and how these people got started with R. 

####Task 1 - read four stories from https://whyiuser.wordpress.com/
Go to the website, pick a story that looks like it could be interesting and answer the following questions. Repeat four times.

**Story #1:**

1. What is the R user's name? 
    
    +  James Curley 

2. What topic do they work on?
    
    +  Neurobiology of social behavior

3. Which answer did you find most surprising / what did you learn from reading their story?

    +  The most interesting answer was about how long he had been using R. apparenly, he      learned the language in a few months and the community in stackoverflow was of           great help. 

**Story #2:**

1. What is the R user's name? 

    +  Robert M Flight

2. What topic do they work on? 

    +  Bioinformatic of multi-omics

3. Which answer did you find most surprising / what did you learn from reading their story?  

    +  I found interesting that he was the second person to mention how easy it was for him to go from his raw data to visualizing the data in R.

**Story #3:**

1. What is the R user's name?

    +  Paola Cognigni
    
2. What topic do they work on?

    +  Drosophila neuroscience

3. Which answer did you find most surprising / what did you learn from reading their story?  

    +  Amazingly, this person started using R as desperate alternative to the typical statistical software, and learned the language through google.


**Story #4:**

1. What is the R user's name?

    +  Callin Switzer.

2. What topic do they work on?

    +  Biomechanics and animal behavior.

3. Which answer did you find most surprising / what did you learn from reading their story?  

    +  Once again, this person mentions how great the R community is online. this is very motivational because I won't be alone as I am learning.



####Task 2 - summarize

After reading several stories about people who use R, is there anything problem that you think R can help you to solve? Is there anything particular that caught your interest?

  +  I think doing statistics with R will make it easier for me because it will understand from the beginning the way that I am organizing my data. Unlike other software that requires me to reorganize my data in order to fit their format.

Is there anything that didn't make sense to you or was unexpected? 

  +  I really can't understand how these people learned R language just by using Google. so far, the language seems pretty complicated. 


####Task 3 - share with your neighbor
Compare notes with at least one neighbor. Why did you neighbor choose the stories he or she read? Did you pick up something different? Did the stories change your ideas about R?

  +  we came to the conclusion that most people actually like the same things about R: the community, the visualization of data, and how easy it is to share your code as well as use other people's.

**Finished!** 

Name: Manuel Rosero

Date: 10/27/16

***

#Worksheet 3 - Do chapter 1 of online R tutorial https://www.codeschool.com/courses/try-r

You need to create a login for Codeschool, then you get started with the R class.  
For this worksheet, you'll do chapter 1. 

1. Do you see any differences with Perl? Write down at least 3 differences

    +  R makes it easier to move files around. 
    +  R will give you answers to a command in the form of True and False.
    +  when you ask for help in R, it gives you detailed information on how to input the arguments, and exactly what kind of arguments are required to properly run a command.


2. How would you ask R to multiply 7 and 8? Or to divide 7 by 8? 

      `7*8 or 7/8`


3. Which of the following expressions would return a logical (or boolean) value? 

#####<span style="color:red">The correct answers are the ones crossed out:</span>

* A. ~~`3 < 4`~~ 
* B. ~~`3 == 4`~~
* C. `x <- 4`
* D. `4 -> x`

4. Can you assign a logical value to a variable called "y"? How would you assign FALSE to a variable called "y"? 

  +  `>y<-False`

5. Name three functions you learned in the tutorial. What do they do? 

  + `>sum(x,y,z)` supposing that x,y, and z are numbers, this function will add the numbers stated as the arguments.


6. What is the function you use to list all the files in your current directory? 

  +  `>list.files()`

7. What is the function you use to run all the code in a file called "file.R"? 

  +  `>source("file.R")`

8. Do you have any questions about the tutorial? 

  +  No, the tutorial was very straight forward.

**Finished!**

Name: 


Date:  

***

#Worksheet 4 - Do chapter 2 of online R tutorial http://tryr.codeschool.com/

Login to Codeschool and do chapter 2.

1. Define the following data structures? What do you find written in them?

Boolean: **logical values (True & False)**

Numeric: **any combination of numbers, including decimals.**

String: **text, including any letters from the alphabet.** 


2. What happens if you try to combine in a vector a Boolean, a numeric and a string? 

  +  the vector cannot hold values with different modes. Therefore, if you add values with different modes to a vector, it will automatically convert them into a single mode (character) 

3. What would be the result of this piece of code: `seq(1, 2, 0.1)`

```
> seq(1, 2, 0.1)
[1] 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0
```

4. A vector can have names. How do you call an element of a vector by its name

  +In order to do this, the vector should already have names assigned to the values using the function `names()`. then, in order to call an element of a vector by its name, you would have to write down the variable (lets call it x) and put in brackets the name that you are trying to call. for example: `x[name]`

5. Suppose you'd run this code to make a vector:  
`sentence <- c("I", "am", "not", "learning", "R", "!", "!")` and then you'd run this code: `sentence[c(1,2,4,5)]`  
What would be the output? 

```
> sentence <- c("I", "am", "not", "learning", "R", "!", "!")
> sentence[c(1,2,4,5)]
[1] "I"        "am"       "learning" "R"  
```

Does R start counting at 0 or at 1?

  +  unlike perl's, R starts counting at 1.

Is this different from Perl? 

  +  yes, it is different. Perl starts counting from 0.

6. In chapter 2 of the online R tutorial on Codeschool, you'll learn how to make two kinds of plots. What are they? What functions do you use to make them? In each case, what goes on the x-axis and what on the y-axis? 

  +  the first plot we learned to make was a barplot, using the function `barplot()`. in this case, assuming the vector has assigned names, the names would be on the X-axis and the values (hopefully numeric) will be on the y-axis.
  +  the second type of plot we learned how to make was a scatter plot, using the function `plot(x,y)`. in this type of plot, the first argument should represent the values for the x-axis and the second argument should represent the values for the y-axis.



**Finished!** 

Name: Manuel Rosero

Date: 10/27/16
